import type { Registry } from "./types";

// Generated by scripts/build-registry.js — do not edit by hand.
// Run `pnpm build` (or `node scripts/build-registry.js`) to regenerate.
let _registry: Registry;

try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  _registry = (require("./generated") as { registry: Registry }).registry;
} catch {
  _registry = {};
}

export const registry: Registry = _registry;

export function getComponent(name: string): Registry[string] | undefined {
  return registry[name.toLowerCase()];
}

export function listComponents(): string[] {
  return Object.keys(registry).sort();
}

/** Resolve a component + all transitive `componentDependencies` (BFS). */
export function resolveComponents(names: string[]): string[] {
  const resolved = new Set<string>();
  const queue = names.map((n) => n.toLowerCase());

  while (queue.length > 0) {
    const name = queue.shift()!;
    if (resolved.has(name)) continue;
    resolved.add(name);
    const entry = registry[name];
    if (entry) {
      for (const dep of entry.componentDependencies) {
        if (!resolved.has(dep)) queue.push(dep);
      }
    }
  }

  return [...resolved];
}

export type { Registry, RegistryEntry, RegistryFile } from "./types";
